version: '3'
volumes:
  apps:
  mviewerstudio_config:

services:

  # Minimalist composition. It is exposing mviewer on port 5001 to match the config-python-sample.json and
  # reduce exposure to breakage.

  # Python version
  mviewerstudio-python:
    build:
      context: .
      dockerfile: docker/Dockerfile-python-backend
    image: mviewer/mviewerstudio:python-latest
    ports:
      - "8080:8000"
    environment:
      - CONF_PATH_FROM_MVIEWER=apps/store
      - CONF_PUBLISH_PATH_FROM_MVIEWER=apps/public
      - DEFAULT_ORG=my_org
      - EXPORT_CONF_FOLDER=/home/apprunner/apps/store
      - MVIEWERSTUDIO_PUBLISH_PATH=/home/apprunner/apps/public
      - MVIEWERSTUDIO_URL_PATH_PREFIX=mviewerstudio/
    volumes:
      - "apps:/home/apprunner/apps"
      - "./config-python-sample.json:/home/apprunner/mviewerstudio_backend/static/apps/config.json"

  mviewer:
    depends_on:
      - mviewerstudio-python
    # this image is automatically built in
    # the mviewer/mviewer github repository
    # See https://github.com/mviewer/mviewer/pull/236
    image: mviewer/mviewer
    ports:
      - "5051:80"
    volumes:
        - "apps:/usr/share/nginx/html/apps"
#